apiVersion: v1
kind: Service
metadata:
  annotations:
    nautilus.dellemc.com/http-ingress: rest
    nautilus.dellemc.com/http-ingress-name: psearch-api
  labels:
    app: pravega-search
    component: psearch-resthead
    project-name: psearch
    security-resource: psearch-psearch
  name: psearch-resthead-svc
  namespace: psearch
spec:
  ports:
  - name: rpc
    port: 9191
    protocol: TCP
    targetPort: 9191
  - name: rest
    port: 9098
    protocol: TCP
    targetPort: 9098
  selector:
    component: psearch-resthead
  type: LoadBalancer

