apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: pravega-cluster
    meta.helm.sh/release-namespace: nautilus-pravega
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
  creationTimestamp: "2022-04-07T05:45:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pravega-cluster
    app.kubernetes.io/version: 0.12.0-1
    helm.sh/chart: nautilus-pravega-1.4-W9-2-42cb54c13
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
      f:status:
        f:phase: {}
    manager: decks-install-linux-amd64
    operation: Update
    time: "2022-04-07T05:45:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:volume.beta.kubernetes.io/storage-provisioner: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-04-07T05:45:05Z"
  name: nautilus-pravega-tier2
  namespace: nautilus-pravega
  resourceVersion: "15082230"
  selfLink: /api/v1/namespaces/nautilus-pravega/persistentvolumeclaims/nautilus-pravega-tier2
  uid: 14578a4f-63e4-4a15-8e43-6c3e69c11c98
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs
  volumeMode: Filesystem
status:
  phase: Pending
