apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sofood-pv-claim
  namespace: aaa
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
